SET IDENTITY_INSERT [dbo].[Gender] ON
INSERT INTO [dbo].[Gender] ([Id], [Symbol], [Description]) VALUES (1, N'M', N'Male')
INSERT INTO [dbo].[Gender] ([Id], [Symbol], [Description]) VALUES (2, N'F', N'Female')
SET IDENTITY_INSERT [dbo].[Gender] OFF


SET IDENTITY_INSERT [dbo].[Producers] ON
INSERT INTO [dbo].[Producers] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (1, N'Patrick', NULL, N'Crowley', N'Patrick Crowley is a producer and assistant director, known for The Bourne Ultimatum (2007), The Bourne Supremacy (2004) and The Bourne Identity (2002). He is married to Cathleen Summers.', N'1954-12-04 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))
  INSERT INTO [dbo].[Producers] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (2, N'Steven', NULL, N'Spielberg', N'One of the most influential personalities in the history of cinema, Steven Spielberg is Hollywood''s best known director and one of the wealthiest filmmakers in the world. He has an extraordinary number of commercially successful and critically acclaimed credits to his name, either as a director, producer or writer.', N'1946-12-18 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))  
  INSERT INTO [dbo].[Producers] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (3, N'Nicole', N'Paradis', N'Grindle', N'Nicole Paradis Grindle is a producer, known for Incredibles 2 (2018), The Incredibles (2004) and Inside Out (2015).', N'0001-01-01 00:00:00', (SELECT TOP(1) [Id]
  FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'F'))  
  INSERT INTO [dbo].[Producers] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (4, N'Vidhu', N'Vinod', N'Chopra', N'Vidhu Vinod Chopra made his directorial debut with Murder At Monkey Hill in 1976 that won him the National Award, which is the top honor given by the Government of India. Two years later, in 1978, this young FTII (Film & Television Institute of India) graduate made a documentary film called An Encounter with Faces, which was nominated for the Academy Awards in 1979. The poignant documentary highlighting the plight of India''s destitute children, also won the Grand Prix at the Tampere International Short Film Festival. While critical praise and recognition came to him with these early works, Chopra then went on to make his first mainstream Hindi film called Sazaaye Maut (Death Row) in 1981. Critical and popular acclaim is hard to come by simultaneously, Chopra is one producer - director who has perfected the art and his body of work is testimony to this. Movies like Khamosh, Parinda, 1942: A Love Story, Kareeb and Mission Kashmir, which were directed by Chopra, were hailed by critics and audiences alike - thus bridging the gap between critical and popular cinema.', N'0001-01-01 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))  
  INSERT INTO [dbo].[Producers] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (5, N'Kevin', NULL, N'Feige', N'Kevin Feige was born on June 2, 1973 in Boston, Massachusetts, USA. He is a producer, known for Guardians of the Galaxy (2014), Captain America: The First Avenger (2011) and Iron Man (2008). He is married to Caitlin Feige.', N'1973-06-02 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))  
  INSERT INTO [dbo].[Producers] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (6, N'Stan', NULL, N'Lee', N'Stan Lee is an American comic-book writer, editor, and publisher, who was formerly executive vice president and publisher of Marvel Comics.

Stan was born in New York City, to Celia (Solomon) and Jack Lieber, a dress cutter. His parents were Romanian Jewish immigrants. Lee co-created Spider-Man, the Hulk, Doctor Strange, the Fantastic Four, Iron Man, Daredevil, Thor, the X-Men, and many other fictional characters, introducing a thoroughly shared universe into superhero comic books. In addition, he challenged the comics'' industry''s censorship organization, the Comics Code Authority, indirectly leading to it updating its policies. Lee subsequently led the expansion of Marvel Comics from a small division of a publishing house to a large multimedia corporation.', N'1922-12-28 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))  
SET IDENTITY_INSERT [dbo].[Producers] OFF


SET IDENTITY_INSERT [dbo].[Movies] ON
INSERT INTO [dbo].[Movies] ([Id], [Name], [Plot], [PosterUrl], [ReleaseYear], [ProducerId]) VALUES (1, N'Jurassic World: Fallen Kingdom', N'When the island''s dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.', N'posters/Jurassic World - Fallen Kingdom.jpg', 2018, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Producers] where FirstName = 'Steven' and LastName = 'Spielberg'))
INSERT INTO [dbo].[Movies] ([Id], [Name], [Plot], [PosterUrl], [ReleaseYear], [ProducerId]) VALUES (2, N'Incredibles 2', N'Bob Parr (Mr. Incredible) is left to care for the kids while Helen (Elastigirl) is out saving the world.', N'posters/Incredibles2.jpg', 2018, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Producers] where FirstName = ' Nicole' and LastName = 'Grindle' and MiddleName = 'Paradis'))
INSERT INTO [dbo].[Movies] ([Id], [Name], [Plot], [PosterUrl], [ReleaseYear], [ProducerId]) VALUES (3, N'Black Panther', N'T''Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country''s past.', N'posters/Black Panther.jpg', 2018, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Producers] where FirstName = 'Stan' and LastName = 'Lee'))
SET IDENTITY_INSERT [dbo].[Movies] OFF


SET IDENTITY_INSERT [dbo].[Actors] ON
INSERT INTO [dbo].[Actors] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (1, N'Chris', NULL, N'Pratt', N'Christopher Michael Pratt is an American film and television actor.', N'1979-06-21 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))
INSERT INTO [dbo].[Actors] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (2, N'Bryce', N'Dallas', N'Howard', N'Bryce Dallas Howard was born on March 2, 1981, in Los Angeles, California. She was conceived in Dallas, Texas (the reason for her middle name). Her father, Ron Howard, is a former actor turned Oscar-winning director.', N'1981-03-02 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'F'))
INSERT INTO [dbo].[Actors] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (3, N'Chadwick', NULL, N'Boseman', N'Chadwick Boseman is an American actor. He is known for his portrayal of T''Challa / Black Panther in the Marvel Cinematic Universe (since 2016), particularly in Black Panther (2018), and for his starring roles in as Jackie Robinson in 42 (2013), James Brown in Get on Up (2014), and Thurgood Marshall in Marshall (2017).', N'1977-11-29 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))
INSERT INTO [dbo].[Actors] ([Id], [FirstName], [MiddleName], [LastName], [Bio], [DOB], [SexId]) VALUES (4, N'Craig', N'T.', N'Nelson', N'Craig T. Nelson was born on April 4, 1944 in Spokane, Washington, USA as Craig Theodore Nelson. He is an actor and producer, known for The Incredibles (2004), Coach (1989) and Poltergeist (1982). He has been married to Doria Cook-Nelson since 1987.', N'1944-04-04 00:00:00', (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Gender] where Symbol = 'M'))
SET IDENTITY_INSERT [dbo].[Actors] OFF


SET IDENTITY_INSERT [dbo].[MovieActorMappings] ON
INSERT INTO [dbo].[MovieActorMappings] ([Id], [MovieId], [ActorId]) VALUES (1, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Jurassic World: Fallen Kingdom'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Actors] where FirstName = 'Chris' and LastName = 'Pratt'))
INSERT INTO [dbo].[MovieActorMappings] ([Id], [MovieId], [ActorId]) VALUES (2, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Jurassic World: Fallen Kingdom'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Actors] where FirstName = 'Bryce' and LastName = 'Howard' and MiddleName = 'Dallas'))
INSERT INTO [dbo].[MovieActorMappings] ([Id], [MovieId], [ActorId]) VALUES (3, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Black Panther'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Actors] where FirstName = 'Chadwick' and LastName = 'Boseman'))
INSERT INTO [dbo].[MovieActorMappings] ([Id], [MovieId], [ActorId]) VALUES (4, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Incredibles 2'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Actors] where FirstName = 'Craig' and LastName = 'Nelson' and MiddleName = 'T.'))
SET IDENTITY_INSERT [dbo].[MovieActorMappings] OFF


SET IDENTITY_INSERT [dbo].[MovieProducerMappings] ON
INSERT INTO [dbo].[MovieProducerMappings] ([Id], [MovieId], [ProducerId]) VALUES (1, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Jurassic World: Fallen Kingdom'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Producers] where FirstName = 'Steven' and LastName = 'Spielberg'))
INSERT INTO [dbo].[MovieProducerMappings] ([Id], [MovieId], [ProducerId]) VALUES (2, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Black Panther'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Producers] where FirstName = 'Stan' and LastName = 'Lee'))
INSERT INTO [dbo].[MovieProducerMappings] ([Id], [MovieId], [ProducerId]) VALUES (3, (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Movies] where Name = 'Incredibles 2'), (SELECT TOP(1) [Id] FROM [MovieDatabase].[dbo].[Producers] where FirstName = 'Nicole' and LastName = 'Grindle' and MiddleName = 'Paradis'))
SET IDENTITY_INSERT [dbo].[MovieProducerMappings] OFF
